Use `bazelisk` instead of `bazel`.
This prevents errors during `release/deploy-to-maven-central.sh` like this one:

```
ERROR: The project you're trying to build requires Bazel 8.3.0 (specified in /usr/local/google/home/cpovirk/clients/flogger-purple/flogger/.bazelversion), but it wasn't found in /usr/bin.
```
RELNOTES=n/a
PiperOrigin-RevId: 786714644